name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: check code formatting, linting, and types
        run: deno task check

      - name: run tests
        run: deno task test
